### ISSUE TITLE
Add NeuroVault extraction

### ISSUE THREAD

**Issue by adelavega** [neuroquery/pubget#25]
Might be helpful to automate the NV link extraction based on regex pattern matching on links

**Comment by jeromedockes** [comment]
why not -- do you mean like having separate PMCID x neurovault collection ID and PMCID x neurovault image ID files besides the links.csv?

**Comment by adelavega** [comment]
indeed

**Comment by jeromedockes** [comment]
@adelavega  can you confirm that all image links will look like `.*neurovault.org/images/(\d+).*` and all collections like `.*neurovault.org/collections/(\d+).*`, where the captured group is the ID?

**Comment by adelavega** [comment]
Two changes to that:
 - First, there are these two aliases: `identifiers.org/neurovault.collection:(\w*)` and `identifiers.org/neurovault.image:(\d*)`
 - Also note that I used `\w` for collection, as private links are actually alphanumeric. This is not actually the collection id, but it can be resolved to one

**Comment by jeromedockes** [comment]
thanks!
