### ISSUE TITLE
still need data dir when using alias option?

### ISSUE THREAD

**Issue by koudyk** [neuroquery/pubget#36]
- I just pulled pubget and installed it with `pip install -e .` in the pubget folder
- I ran `pubget run -q "fMRI[Abstract] AND music[Title]" --labelbuddy --alias fmri_music`
- I got this error: `pubget run: error: the following arguments are required: data_dir`

On the poster, we use the alias option without specifying a data directory. Is this how it's supposed to work? Or do we need both? If so, maybe we should update the code on the poster.

**Comment by jeromedockes** [comment]
sorry I missed this! yes we still need the `data_dir`, which is the root of all pubget data. the alias symlink and the query directory go inside the `data_dir`. As you know we fixed the poster. what we could consider is have a default for the data dir, such as the current working directory. It would certainly make some examples look a bit simpler, but I think in most cases users will want to specify a specific data directory. WDYT?
